/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { Mesh, MeshStandardMaterial } from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    BirchTree_2_1: Mesh;
    BirchTree_2_2: Mesh;
    BirchTree_2_3: Mesh;
    BirchTree_2_4: Mesh;
  };
  materials: {
    ["White.001"]: MeshStandardMaterial;
    ["Black.001"]: MeshStandardMaterial;
    ["DarkGreen.001"]: MeshStandardMaterial;
    ["Green.001"]: MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/nature_pack/BirchTree_2.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.BirchTree_2_1.geometry}
          material={materials["White.001"]}
        />
        <mesh
          geometry={nodes.BirchTree_2_2.geometry}
          material={materials["Black.001"]}
        />
        <mesh
          geometry={nodes.BirchTree_2_3.geometry}
          material={materials["DarkGreen.001"]}
        />
        <mesh
          geometry={nodes.BirchTree_2_4.geometry}
          material={materials["Green.001"]}
        />
      </group>
    </group>
  );
}
