/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { Mesh, MeshStandardMaterial } from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Bush_Snow_2_1: Mesh;
    Bush_Snow_2_2: Mesh;
  };
  materials: {
    Snow: MeshStandardMaterial;
    Green: MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/nature_pack/Bush_Snow_2.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Bush_Snow_2_1.geometry}
          material={materials.Snow}
        />
        <mesh
          geometry={nodes.Bush_Snow_2_2.geometry}
          material={materials.Green}
        />
      </group>
    </group>
  );
}
