/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Mesh, MeshStandardMaterial } from "three";

type GLTFResult = GLTF & {
  nodes: {
    Flowers_1: Mesh;
    Flowers_2: Mesh;
    Flowers_3: Mesh;
  };
  materials: {
    Green: MeshStandardMaterial;
    Cyan: MeshStandardMaterial;
    Yellow: MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/nature_pack/Flowers.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Flowers_1.geometry} material={materials.Green} />
        <mesh geometry={nodes.Flowers_2.geometry} material={materials.Cyan} />
        <mesh geometry={nodes.Flowers_3.geometry} material={materials.Yellow} />
      </group>
    </group>
  );
}
