/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Mesh, MeshStandardMaterial } from "three";

type GLTFResult = GLTF & {
  nodes: {
    Tree3_1: Mesh;
    Tree3_2: Mesh;
  };
  materials: {
    Leaves: MeshStandardMaterial;
    Tree: MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/simple_nature_pack/Tree3.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Tree3_1.geometry} material={materials.Leaves} />
        <mesh geometry={nodes.Tree3_2.geometry} material={materials.Tree} />
      </group>
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/simple_nature_pack/Tree3.glb");
