/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useAnimationsWithCleanup } from "@hooks/useAnimationsWithCleanup";
import { GLTF } from "three-stdlib";
import {
  SkinnedMesh,
  Bone,
  MeshStandardMaterial,
  AnimationClip,
  Group,
} from "three";

type GLTFResult = GLTF & {
  nodes: {
    ClownFish_1: SkinnedMesh;
    ClownFish_2: SkinnedMesh;
    ClownFish_3: SkinnedMesh;
    Root: Bone;
  };
  materials: {
    Outline: MeshStandardMaterial;
    Body: MeshStandardMaterial;
    Stripes: MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ActionName = "Armature|Swim";
interface GLTFAction extends AnimationClip {
  name: ActionName;
}

export function useFish3() {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/fish_pack/Fish3.glb"
  ) as unknown as GLTFResult;

  return { nodes, materials };
}

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<Group>(null!);
  const { nodes, materials, animations } = useGLTF(
    "/3d-assets/glb/fish_pack/Fish3.glb"
  ) as unknown as GLTFResult;
  const { actions } = useAnimationsWithCleanup(animations, group.current);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.Root} />
          </group>
          <group name="ClownFish" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh
              name="ClownFish_1"
              geometry={nodes.ClownFish_1.geometry}
              material={materials.Outline}
              skeleton={nodes.ClownFish_1.skeleton}
            />
            <skinnedMesh
              name="ClownFish_2"
              geometry={nodes.ClownFish_2.geometry}
              material={materials.Body}
              skeleton={nodes.ClownFish_2.skeleton}
            />
            <skinnedMesh
              name="ClownFish_3"
              geometry={nodes.ClownFish_3.geometry}
              material={materials.Stripes}
              skeleton={nodes.ClownFish_3.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/fish_pack/Fish3.glb");
