/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useAnimationsWithCleanup } from "@hooks/useAnimationsWithCleanup";
import { GLTF } from "three-stdlib";
import {
  AnimationClip,
  Bone,
  Group,
  MeshStandardMaterial,
  SkinnedMesh,
} from "three";

type GLTFResult = GLTF & {
  nodes: {
    Fish_1: SkinnedMesh;
    Fish_2: SkinnedMesh;
    Fish_3: SkinnedMesh;
    Root: Bone;
  };
  materials: {
    Bottom: MeshStandardMaterial;
    Top: MeshStandardMaterial;
    Fins: MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ActionName = "Armature|Swim";
interface GLTFAction extends AnimationClip {
  name: ActionName;
}

export function useFish1() {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/fish_pack/Fish1.glb"
  ) as unknown as GLTFResult;

  return { nodes, materials };
}

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<Group>(null!);
  const { nodes, materials, animations } = useGLTF(
    "/3d-assets/glb/fish_pack/Fish1.glb"
  ) as unknown as GLTFResult;
  const { actions } = useAnimationsWithCleanup(animations, group.current);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.Root} />
          </group>
          <group name="Fish" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh
              name="Fish_1"
              geometry={nodes.Fish_1.geometry}
              material={materials.Bottom}
              skeleton={nodes.Fish_1.skeleton}
            />
            <skinnedMesh
              name="Fish_2"
              geometry={nodes.Fish_2.geometry}
              material={materials.Top}
              skeleton={nodes.Fish_2.skeleton}
            />
            <skinnedMesh
              name="Fish_3"
              geometry={nodes.Fish_3.geometry}
              material={materials.Fins}
              skeleton={nodes.Fish_3.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/fish_pack/Fish1.glb");
