/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useAnimationsWithCleanup } from "@hooks/useAnimationsWithCleanup";
import { GLTF } from "three-stdlib";
import {
  SkinnedMesh,
  Bone,
  MeshStandardMaterial,
  AnimationClip,
  Group,
} from "three";

type GLTFResult = GLTF & {
  nodes: {
    MantaRay_1: SkinnedMesh;
    MantaRay_2: SkinnedMesh;
    Root: Bone;
  };
  materials: {
    Bottom: MeshStandardMaterial;
    Top: MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ActionName = "Armature|Swim";
interface GLTFAction extends AnimationClip {
  name: ActionName;
}

export function useMantaRay() {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/fish_pack/Manta_ray.glb"
  ) as unknown as GLTFResult;

  return { nodes, materials };
}

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<Group>(null!);
  const { nodes, materials, animations } = useGLTF(
    "/3d-assets/glb/fish_pack/Manta_ray.glb"
  ) as unknown as GLTFResult;
  const { actions } = useAnimationsWithCleanup(animations, group.current);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.Root} />
          </group>
          <group
            name="MantaRay"
            position={[0, 0, 0.8]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <skinnedMesh
              name="MantaRay_1"
              geometry={nodes.MantaRay_1.geometry}
              material={materials.Bottom}
              skeleton={nodes.MantaRay_1.skeleton}
            />
            <skinnedMesh
              name="MantaRay_2"
              geometry={nodes.MantaRay_2.geometry}
              material={materials.Top}
              skeleton={nodes.MantaRay_2.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/fish_pack/Manta_ray.glb");
