/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useAnimationsWithCleanup } from "@hooks/useAnimationsWithCleanup";
import { useGLTF } from "@react-three/drei";
import { useRef } from "react";
import {
  AnimationClip,
  Bone,
  Group,
  MeshStandardMaterial,
  SkinnedMesh,
} from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Shark_1: SkinnedMesh;
    Shark_2: SkinnedMesh;
    Root: Bone;
  };
  materials: {
    Bottom: MeshStandardMaterial;
    Top: MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ActionName = "Armature|Swim";
interface GLTFAction extends AnimationClip {
  name: ActionName;
}

export function useShark() {
  const { nodes, materials } = useGLTF(
    "/3d-assets/glb/fish_pack/Shark.glb"
  ) as unknown as GLTFResult;

  return { nodes, materials };
}

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<Group>(null!);
  const { nodes, materials, animations } = useGLTF(
    "/3d-assets/glb/fish_pack/Shark.glb"
  ) as unknown as GLTFResult;
  const { actions } = useAnimationsWithCleanup(animations, group.current);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group
            name="Armature"
            position={[0, 0, 0.45]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <primitive object={nodes.Root} />
          </group>
          <group
            name="Shark"
            position={[0, 0.33, 0.37]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={159.42}
          >
            <skinnedMesh
              name="Shark_1"
              geometry={nodes.Shark_1.geometry}
              material={materials.Bottom}
              skeleton={nodes.Shark_1.skeleton}
            />
            <skinnedMesh
              name="Shark_2"
              geometry={nodes.Shark_2.geometry}
              material={materials.Top}
              skeleton={nodes.Shark_2.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/3d-assets/glb/fish_pack/Shark.glb");
